# Generated by Django 2.2.4 on 2019-09-03 22:53

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('resumo', ckeditor.fields.RichTextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads', verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
