# Generated by Django 2.2.4 on 2019-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcar_jogo',
            name='placarCasa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marcar_jogo',
            name='placarFora',
            field=models.IntegerField(null=True),
        ),
    ]
